# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 500)
        MainWindow.setMinimumSize(QtCore.QSize(500, 500))
        MainWindow.setMaximumSize(QtCore.QSize(500, 500))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 30, 151, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 131, 41))
        self.label_2.setObjectName("label_2")
        self.input_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_1.setGeometry(QtCore.QRect(200, 100, 251, 20))
        self.input_1.setObjectName("input_1")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 166, 131, 20))
        self.label_3.setObjectName("label_3")
        self.input_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_2.setGeometry(QtCore.QRect(200, 160, 251, 20))
        self.input_2.setObjectName("input_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(260, 360, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 280, 121, 16))
        self.label_4.setObjectName("label_4")
        self.input_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_3.setGeometry(QtCore.QRect(200, 270, 251, 20))
        self.input_3.setObjectName("input_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 220, 131, 16))
        self.label_5.setObjectName("label_5")
        self.yes_Button = QtWidgets.QPushButton(self.centralwidget)
        self.yes_Button.setGeometry(QtCore.QRect(260, 220, 75, 23))
        self.yes_Button.setObjectName("yes_Button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Password Manger "))
        self.label.setText(_translate("MainWindow", "Password Manager "))
        self.label_2.setText(_translate("MainWindow", "Enter the website\'s link"))
        self.label_3.setText(_translate("MainWindow", "User\'s Email "))
        self.pushButton.setText(_translate("MainWindow", "Save "))
        self.label_4.setText(_translate("MainWindow", "Password "))
        self.label_5.setText(_translate("MainWindow", "Generate The Password?"))
        self.yes_Button.setText(_translate("MainWindow", "Yes"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
